### ISSUE TITLE
Nothing renders on admin portal

### ISSUE THREAD

**Issue by Jessica-Ryan** [sveetch/djangocodemirror#25]
I am trying to render a TextField on the admin portal that highlights the syntax for html using the CodeMirrorWidget though nothing is rendering. I have followed the instructions in the docs:

settings.py:

```
from djangocodemirror.settings import *

CODEMIRROR_MODES.update({
    'xml': {
        'modes': ['html'],
        'htmlMode': True,
        'matchBrackets': True,
        'extraKeys': {"Ctrl-Space": "autocomplete"},
        'addons': [
            "CodeMirror/addon/edit/matchbrackets.js",
            "CodeMirror/addon/hint/show-hint.js",
            "CodeMirror/addon/hint/css-hint.js",
        ],
        'extra_css': [
            "CodeMirror/addon/hint/show-hint.css",
        ],
    },
})
```
admin.py
```
from django.contrib import admin
from django.db import models
from djangocodemirror.widgets import CodeMirrorWidget

class FrontendAdminSite(admin.AdminSite):
frontend_admin_site = FrontendAdminSite(name='frontend_admin')

@admin.register(Template, site=frontend_admin_site)
class TemplateAdmin(admin.ModelAdmin):

    list_display = ("name", "template")
    search_fields = ("name__startswith",)
    formfield_overrides = {
        models.TextField: {
            'widget': CodeMirrorWidget(
                attrs={
                    'rows': '10',
                    'cols': '100'
                }
            )
        }
    }
```

Despite the above, I am just getting a standard textfield on the admin page. What should I be doing to see the CodeMirror editor?

![Screenshot from 2022-04-26 19-45-01](https://user-images.githubusercontent.com/85116857/165361534-43baa55a-390a-4b68-aa90-3fd123771ee4.png)

**Comment by sveetch** [comment]
The form field and widget require a little bit of Javascript to instantiate the Codemirror JS stuff on an input. So either you can instantiate the widget yourself and you can give the argument `embed_config = True` (that will put the required JS right after the input HTML) or more easier you directly use the widget [CodeMirrorAdminWidget](https://djangocodemirror.readthedocs.io/en/latest/library_references/widgets.html#djangocodemirror.widgets.CodeMirrorAdminWidget) which already set this option to True and automatically insert required JS stuff.

When it's done, reload and check the view, if you don't see Codemirror on your input, check the browser console for JS errors or 404 on its libraries.

**Comment by sveetch** [comment]
Disclaimer: my app needs some update, i'm not sure it is fully compatible yet with Django 3.x or 4.x

**Comment by Jessica-Ryan** [comment]
Thanks.
I installed django-codemirror-widget and used it as follows:

settings.py:
`CODEMIRROR_PATH = os.path.join(STATIC_URL, 'codemirror-5.65.3')`

admin.py:
```
@admin.register(Template, site=frontend_admin_site)
class TemplateAdmin(admin.ModelAdmin):

    codemirror_widget = CodeMirrorTextarea(
        mode="xml",
        theme="material-ocean",
        config={
            'fixedGutter': True,
        },
    )

    list_display = ("name", "template")
    search_fields = ("name__startswith",)
    formfield_overrides = {
        models.TextField: {
            'widget': codemirror_widget
        }
    }
```
